### ISSUE TITLE
Safari and multiple hashtags

### ISSUE THREAD

**Issue by Russkowski** [briangonzalez/jquery.arbitrary-anchor.js#9]
First of all thank you very much for your script, good job.

Testing my site with all major browsers showed me up an issue without beeing an issue.

Simply: There is only one hashtag allowed in URLs to be valid (http spec).

All Browsers ignore this but Safari changes URL automatically, this means e.g.

mydomain.com/faq/##howtopay 
will be changed automatically to
mydomain.com/faq/#%23howtopay 

This breaks up the logic of your URL handler = no more scrolling to anchor with the given ID. Is there any workaround to use another character or code snippet to avoid this?

Thank you in advance.

Related links:
http://en.wikipedia.org/wiki/Fragment_identifier
http://stackoverflow.com/questions/4433119/safari-multiple-hashtags
http://www.kriesi.at/support/topic/deeplinks-to-layer-slider-slides-dont-work-safari-escapes-hashtag/

**Comment by briangonzalez** [comment]
Good find! I would suggest giving it a data-attribute or class, and not use an ID.
